id: A31980F43
base_file: f014C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:58:07.099180
  last_modified_at: 2022-05-30 22:58:07.099189
