id: A31980F43
base_file: fF376.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:58:07.130605
  last_modified_at: 2022-05-30 22:58:07.130612
