id: A31980F43
base_file: f99EF.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:58:07.115999
  last_modified_at: 2022-05-30 22:58:07.116006
