id: A31980F43
base_file: f952B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:58:07.111979
  last_modified_at: 2022-05-30 22:58:07.111986
