id: A31980F43
base_file: fC68C.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:58:07.122590
  last_modified_at: 2022-05-30 22:58:07.122593
